x = linspace(0,9,40);

f1 = 1/((2*pi).^0.5) .* (exp((-1/2).*((x - 4.5).^2)));
f2 = 0.5 .* exp(-0.5 .* x);
f3 = repelem( 0.4 , numel(x));

subplot(2,2,[1,3]);
plot(x, f1, 'g--o', ...
    'LineWidth', 2,...
    'MarkerEdgeColor', 'r',...
    'MarkerFaceColor', 'r',...
    'MarkerSize', 4);

subplot(2,2,2);
plot(x, f2, ':', ...
    'LineWidth', 2,...
    'color', 'k');

subplot(2,2,4);
plot(x, f3, 'c-.', ...
    'LineWidth', 1.3, ...
    'color', 'b');
axis([0 9 0 0.6])
legend('Location', 'none', 'Position', [210 250 10 10],'Normal', 'Exponential', 'Uniform');
title('Probability Density Functions');
